# Generated by Django 5.1.3 on 2025-12-12 16:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Executor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("max_tasks", models.IntegerField()),
            ],
            options={
                "db_table": "executors",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (1, "Lowest"),
                            (2, "Low"),
                            (3, "Medium"),
                            (4, "High"),
                            (5, "Highest"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="core.executor",
                    ),
                ),
            ],
            options={
                "db_table": "tasks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="tasks_status_031d4c_idx"),
                    models.Index(fields=["priority"], name="tasks_priorit_a9efa1_idx"),
                    models.Index(fields=["assignee"], name="tasks_assigne_462a05_idx"),
                ],
            },
        ),
    ]
